annotations:
  max_scale_version: 24.04.1
  min_scale_version: 24.04.0
  truecharts.org/category: media
  truecharts.org/max_helm_version: "3.15"
  truecharts.org/min_helm_version: "3.11"
  truecharts.org/train: stable
apiVersion: v2
appVersion: 1.0.0
dependencies:
  - name: common
    version: 24.1.5
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Bridge Snapclient to local Speakers
home: https://truecharts.org/charts/stable/snapclient
keywords:
  - snapclient
  - snapserver
  - music
kubeVersion: '>=1.24.0-0'
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: snapclient
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/snapclient
type: application
version: 13.1.3
